/*
 * ionet
 * Copyright (C) 2021 - present  渔民小镇 （262610965@qq.com、luoyizhu@gmail.com） . All Rights Reserved.
 * # iohao.com . 渔民小镇
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.iohao.example.sdk;


import com.iohao.example.sdk.action.SdkCmd;
import com.iohao.example.sdk.extension.MySocketIdleHook;
import com.iohao.net.app.RunOne;
import com.iohao.net.external.core.ExternalServer;
import com.iohao.net.external.core.config.ExternalGlobalConfig;
import com.iohao.net.external.core.hook.internal.IdleProcessSetting;
import com.iohao.net.external.core.netty.ExternalMapper;
import com.iohao.net.server.LogicServer;
import lombok.extern.slf4j.Slf4j;

import java.util.List;
import java.util.Locale;

/**
 * @author 渔民小镇
 * @date 2024-11-01
 */
@Slf4j
public final class SdkApplication {
    static void main() {
//        CoreGlobalConfig.setting.parseDoc = true;
//        CoreGlobalConfig.setting.print = true;

        // i18n: CHINA or US
        Locale.setDefault(Locale.US);
        new RunOne()
                .setAeron(new AeronLifecycleManager().getAeron())
                .enableCenterServer()
                .setExternalServer(createExternalServer())
                .setLogicServerList(listLogic())
                .startup();
    }

    static List<LogicServer> listLogic() {
        return List.of(
                new SdkLogicServer()
        );
    }

    private static ExternalServer createExternalServer() {
        int externalPort = ExternalGlobalConfig.externalPort;
        extractedAccess();

        // Build ExternalServer https://iohao.github.io/game/docs/overall/external_intro
        var builder = ExternalMapper.builder();
        builder.setPort(externalPort);

        /*
         * https://iohao.github.io/game/docs/external/idle
         * About netty heartbeat. See SocketIdleHandler
         *
         * cn: 创建 IdleProcessSetting，用于心跳相关的设置
         */

        var idleProcessSettingBuilder = IdleProcessSetting.builder()
                .setIdleTime(10)
                .setIdleHook(new MySocketIdleHook());

        builder.setIdleProcessSettingBuilder(idleProcessSettingBuilder);

        return builder.build();
    }

    static void extractedAccess() {
        // https://iohao.github.io/game/docs/external/access_authentication

        var accessAuthenticationHook = ExternalGlobalConfig.accessAuthenticationHook;
        // true: Users must loginVerify before they can access the business methods
        accessAuthenticationHook.setVerifyIdentity(true);
        // Ignore cmd: These ignored routes can be accessed without the need to loginVerify
        accessAuthenticationHook.addIgnoreAuthCmd(SdkCmd.cmd, SdkCmd.loginVerify);
        accessAuthenticationHook.addIgnoreAuthCmd(SdkCmd.cmd);

        /*
         * Notice:
         *     Reject cmd: Routes that deny access to any player.
         *     These action methods will not be generated by the SDK.
         *
         *     sdk 将不会生成这些配置了 Rejection 的 action 方法。
         */
        accessAuthenticationHook.addRejectionCmd(SdkCmd.cmd, SdkCmd.internalAddMoney);
    }
}
